# Agent-Based LLM Arbitrage Platform Configuration
# Production-ready settings for investor demo

platform:
  name: "Agent-Based LLM Arbitrage Platform"
  version: "1.0.0"
  mode: "production"  # development | testing | production
  
# Agent Configuration
agents:
  economic:
    enabled: true
    polling_hours: 1
    data_age_max_hours: 6
    confidence_min: 0.5
    sources:
      fred_api: true
      oecd_api: false  # Optional premium source
    parameters:
      - "CPIAUCSL"    # CPI All Urban Consumers
      - "FEDFUNDS"    # Federal Funds Rate
      - "UNRATE"      # Unemployment Rate
      - "M2SL"        # M2 Money Supply
      - "GDP"         # GDP Growth
      - "VIX"         # Volatility Index
  
  sentiment:
    enabled: true
    window_sec: 30
    min_mention_volume: 50
    polarity_confidence_min: 0.4
    sources:
      twitter_v2: true
      google_trends: true
      reddit_api: true
      news_api: false  # Optional
    keywords:
      - "bitcoin"
      - "BTC"
      - "crypto"
      - "trading"
      - "arbitrage"
  
  price:
    enabled: true
    snapshot_ms: 100
    min_24h_volume_usd: 5000000
    orderbook_levels: 100
    exchanges:
      - "binance"
      - "coinbase"
      - "kraken"
    pairs:
      - "BTC-USDT"
      - "ETH-USDT"
      - "BTC-USD"
      - "ETH-USD"
  
  volume:
    enabled: true
    window_sec: 60
    liquidity_index_min: 0.2
    volume_spike_threshold: 2.0
  
  trade:
    enabled: true
    max_trade_latency_ms: 500
    slippage_estimate_max_pct: 0.02
    vwap_window_sec: 60
  
  image:
    enabled: true
    image_age_max_sec: 60
    visual_confidence_min: 0.6
    heatmap_generation: true
    pattern_recognition: true

# Global Constraints (Hard Limits)
constraints:
  max_open_exposure_pct_of_NAV: 0.03
  api_health_pause_threshold: 2
  event_blackout_sec: 300
  data_freshness_max_sec: 5
  authorized_exchanges_only: true
  max_concurrent_agents: 10
  circuit_breaker_drawdown_pct: 0.05

# Decision Engine Bounds
bounds:
  min_spread_pct_for_execution: 0.005
  llm_confidence_threshold: 0.8
  min_expected_net_profit_usd: 10
  max_hold_time_sec: 3600
  max_simultaneous_trades: 5
  max_slippage_pct_estimate: 0.002
  z_threshold_k: 2.5
  
# AOS (Arbitrage Opportunity Score) Weights
aos_weights:
  price: 0.4
  sentiment: 0.25
  volume: 0.2
  image: 0.05
  risk: -0.1

# Hyperbolic Embedding Configuration
hyperbolic:
  model: "poincare"
  curvature: 1.0
  embedding_dim: 128
  learning_rate: 0.01
  batch_size: 32
  
# LLM Configuration
llm:
  primary_provider: "anthropic"  # anthropic | openai | local
  model: "claude-3-sonnet-20240229"
  max_tokens: 1000
  temperature: 0.1
  timeout_ms: 5000
  fallback_provider: "openai"
  fallback_model: "gpt-4"

# Exchange Configuration
exchanges:
  binance:
    enabled: true
    testnet: true  # Use testnet for demo
    rate_limit_per_sec: 10
    websocket_url: "wss://testnet.binance.vision/ws/"
    rest_url: "https://testnet.binance.vision"
  
  coinbase:
    enabled: true
    sandbox: true  # Use sandbox for demo
    rate_limit_per_sec: 10
    websocket_url: "wss://ws-feed-public.sandbox.exchange.coinbase.com"
    rest_url: "https://api-public.sandbox.exchange.coinbase.com"

# Database Configuration
database:
  type: "sqlite"  # sqlite | postgresql | redis
  path: "./data/arbitrage.db"
  connection_pool_size: 10
  query_timeout_ms: 5000

# Kafka Configuration
messaging:
  kafka:
    enabled: true
    brokers: ["localhost:9092"]
    topics:
      agents_latest: "agents.latest"
      fusion_predictions: "fusion.predictions"
      execution_orders: "execution.orders"
      validation_results: "validation.results"

# Security Configuration
security:
  api_key_rotation_days: 30
  audit_log_retention_days: 365
  encryption_algorithm: "AES-256-GCM"
  rate_limit_requests_per_minute: 100

# Monitoring & Observability
monitoring:
  metrics_collection: true
  performance_tracking: true
  error_reporting: true
  dashboard_refresh_ms: 1000
  
# Backtesting Configuration
backtesting:
  enabled: true
  lookback_days: 30
  walk_forward_window_days: 7
  min_trades_for_validation: 10
  confidence_interval: 0.95

# Risk Management
risk:
  max_position_size_pct: 0.02
  stop_loss_pct: 0.01
  take_profit_pct: 0.005
  max_daily_trades: 50
  cooling_period_minutes: 5