#!/bin/bash

echo "======================================"
echo "🚀 GOMNA PLATFORM DEPLOYMENT CHECK"
echo "======================================"
echo ""
echo "📍 GitHub Pages URL:"
echo "https://gomna-pha.github.io/hypervision-crypto-ai/"
echo ""
echo "📍 Deploy Info Page (Check this first):"
echo "https://gomna-pha.github.io/hypervision-crypto-ai/deploy_info.html"
echo ""
echo "✅ FEATURES TO VERIFY:"
echo ""
echo "1. LIGHT CREAM THEME:"
echo "   - Background should be cream (#FAF7F0)"
echo "   - NO dark backgrounds"
echo "   - Brown text (#3E2723)"
echo ""
echo "2. GOMNA BRANDING:"
echo "   - Title says 'GOMNA' (not Gomna AI)"
echo "   - 3D Cocoa pod logo in top-left"
echo "   - Italic styled text"
echo ""
echo "3. DRAGGABLE PANELS:"
echo "   - All panels can be moved"
echo "   - 'Reset Layout' button in header"
echo "   - 'Toggle Panels' button"
echo ""
echo "4. FOLDABLE PANELS:"
echo "   - Every panel has minimize button (−)"
echo "   - Click to collapse/expand"
echo "   - Execute Trade panel foldable"
echo "   - Live Market Data panel foldable"
echo ""
echo "5. REAL-TIME TRADING:"
echo "   - Live Market Data panel (bottom-left)"
echo "   - Order Execution panel (bottom-right)"
echo "   - Prices auto-update every 30 seconds"
echo "   - CoinGecko API auto-connects"
echo ""
echo "⏱️ DEPLOYMENT TIME:"
echo "GitHub Pages typically takes 2-10 minutes to update."
echo "If not updated, try:"
echo "1. Clear browser cache (Ctrl+F5)"
echo "2. Use incognito/private window"
echo "3. Wait a few more minutes"
echo ""
echo "======================================"
